### ISSUE TITLE
安装有错误？

### ISSUE THREAD

**Issue by zhupeiyuan-2016** [Youthink/Vimrc#1]
![image](https://user-images.githubusercontent.com/24429095/37693635-f1a0fdf8-2cfb-11e8-9719-573cd0ff30c7.png)

**Comment by imfycc** [comment]
如果是第一次打开时出现的，是因为对应的主题还没有安装。第一次打开 vim 时会自动下载相关的插件。之后再打开 vim，就不会有这个报错了。

如果每次打开 vim 都出现这个报错，可能是因为我安装过 `molokai` 这个主题，当时没删除干净，`~/.vimrc` 找到对应的报错行数，改成你喜欢的主题，就行了。
